<?php
/**
 * English labels for custom-agent-inventory.
 */

Dict::Add('EN US', 'English', 'English', array(
	'Class:FunctionalCI/Attribute:agent_guid'       => 'Agent GUID',
	'Class:FunctionalCI/Attribute:agent_guid+'      => 'Identifier generated by itop-agent. Primary reconciliation key; survives renaming, not reimaging.',
	'Class:FunctionalCI/Attribute:agent_last_seen'  => 'Last agent report',
	'Class:FunctionalCI/Attribute:agent_last_seen+' => 'Point in time when itop-agent last delivered data for this CI.',
));
