<?php
/**
 * English labels for custom-agent-inventory.
 */

Dict::Add('EN US', 'English', 'English', array(
	'Class:FunctionalCI/Attribute:agent_guid'       => 'Agent GUID',
	'Class:FunctionalCI/Attribute:agent_guid+'      => 'Identifier generated by itop-agent. Primary reconciliation key; survives renaming, not reimaging.',
	'Class:FunctionalCI/Attribute:agent_last_seen'  => 'Last agent report',
	'Class:FunctionalCI/Attribute:agent_last_seen+' => 'Point in time when itop-agent last delivered data for this CI.',
	'Class:Software/Attribute:agent_match_patterns' => 'Match patterns (agent)',
	'Class:Software/Attribute:agent_match_patterns+' => 'One pattern per line. Plain text matches if contained in the reported software name (case-insensitive). A leading ! excludes. A pattern enclosed in slashes is read as a regular expression. Empty means this entry does not take part in matching.',
));
